### ISSUE TITLE
Parsing File

### ISSUE THREAD

**Issue by PattonK** [skywithin/Ebcdic2Unicode#1]
I keep running into the following:

if (expectedRows % 1 != 0) //Expected number of rows is not a whole number

Not sure what I am doing wrong.  The allBytes.Length = 513260 

LineTemplate lineTemplate = new LineTemplate(857, "BICDU");
                lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_01", FieldType.String, 0, 119));
                lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_02", FieldType.String, 119, 70));
                lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_03", FieldType.String, 189, 35));
                lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_04", FieldType.String, 224, 64));
                lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_05", FieldType.String, 288, 35));
                lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_06", FieldType.String, 323, 35));
                lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_07", FieldType.String, 358, 35));
                lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_08", FieldType.String, 393, 70));
                lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_09", FieldType.String, 463, 105));
                lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_10", FieldType.String, 568, 70));
                lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_11", FieldType.String, 638, 35));
                lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_12", FieldType.String, 673, 105));
                lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_13", FieldType.String, 778, 79));

[EBCDIC_File.zip](https://github.com/maxvagner/Ebcdic2Unicode/files/1763471/EBCDIC_File.zip)

Any assistance would be greatly appreciated.

**Comment by skywithin** [comment]
You specified that line length is 857 bytes. The size of the source data
is  513,260 bytes.  513,260 / 857 = 598.9031505250875 which means you will
have some leftovers at the end which is wrong if your source data is
compounded from multiple lines. If you are absolutely sure that your line
template is correct, you might try reading  857 bytes at a time and feeding
it to the parser.


public void Test_ParseSingleLine_ParsesTestData()
        {
            LineTemplate lineTemplate = new LineTemplate(857, "BICDU");
            lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_01",
FieldType.String, 0, 119));
            lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_02",
FieldType.String, 119, 70));
            lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_03",
FieldType.String, 189, 35));
            lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_04",
FieldType.String, 224, 64));
            lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_05",
FieldType.String, 288, 35));
            lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_06",
FieldType.String, 323, 35));
            lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_07",
FieldType.String, 358, 35));
            lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_08",
FieldType.String, 393, 70));
            lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_09",
FieldType.String, 463, 105));
            lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_10",
FieldType.String, 568, 70));
            lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_11",
FieldType.String, 638, 35));
            lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_12",
FieldType.String, 673, 105));
            lineTemplate.AddFieldTemplate(new FieldTemplate("FIELD_13",
FieldType.String, 778, 79));


            byte[] sourceBytes =
File.ReadAllBytes(@"C:\temp\BICDU_Sample.EBC");
            var processor = new EbcdicParser();

            byte[] lineBytes ;
            int position = 0;

            while (position < sourceBytes.Length)
            {
                if (position + lineTemplate.LineSize > sourceBytes.Length)
                {
                    // Skip leftovers at the end of the file.
                    break;
                }

                lineBytes = ParserUtilities.ReadBytesRange(
                    sourceBytes,
                    length: lineTemplate.LineSize,
                    startPosition: position,
                    throwExceptionIfSourceArrayIsTooShort: false);

                position += lineTemplate.LineSize;

                var line = processor.ParseSingleLine(lineTemplate,
lineBytes);
                var output = line.ToXmlString();
                Debug.WriteLine(output);
            }
        }

**Comment by PattonK** [comment]
Max,

Thank you for your input.  I did not have a copybook to work with on this collection and had made some assumption.  I will do some further investigating and get back to you with my results.
