### ISSUE TITLE
Question:  Why limit decimal positions to 6?

### ISSUE THREAD

**Issue by KennethScott** [skywithin/Ebcdic2Unicode#3]
Hello Max-

I noticed you limit decimal positions to 6 for a given field.  Is that a programmatic limitation or just something you did for the particular set of files you were working with?  We often see fields with many more decimal positions and were just wondering if that could be removed or at least increased?

Specifically the code is in the FieldTemplate class in the ValidateInputParameters method:
![image](https://user-images.githubusercontent.com/823499/39582547-cca3b7e6-4eb3-11e8-81a4-99b9c5530b10.png)

Thank you!

**Comment by skywithin** [comment]
Yes, it was particular to our set of files. I'll remove it from code.

**Comment by KennethScott** [comment]
Great, thank you!
